services:
  api:
    build: ./api
    container_name: chat-api
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - db
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    gpus: all
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_CONTEXT_LENGTH=4096
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_THREADS=4
      - OLLAMA_CPU_OFFLOAD=true
      - OLLAMA_KEEP_ALIVE=1h
    volumes:
      - ./ollama-models:/root/.ollama/models
    ports:
      - '11434:11434'

  web:
    image: nginx:alpine
    container_name: chat-web
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '3001:80'
    depends_on:
      - api
      - ollama

  db:
    image: mariadb:10.9
    container_name: chat-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
